backend:
  name: github
  repo: MUBlockchain/website
  branch: master


media_folder: static/img
public_folder: /img

collections:
  - name: blog
    label: Blog
    folder: src/markdown/blog
    create: true
    fields:
      - { name: path, label: Path, hint: "eg. '/blog/my-blog'" }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: featuredImage, label: Image, widget: image }
  - name: schedule
    label: Event Schedule
    folder: src/markdown/schedule
    create: true
    fields:
      - { name: path, label: Path, hint: "eg. '/events/my-event'" }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: description, label: Event Description, widget: markdown }
      - { name: eventDate, label: Event Date, widget: string }
      - { name: link, label: Link, widget: string }
      - { name: featuredImage, label: Image, widget: image }
  - name: carousel
    label: Carousel
    folder: src/markdown/carousel
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: image, label: Image, widget: image }
      - { name: position, label: Position, widget: number}
  - name: leadership
    label: Leadership
    folder: src/markdown/leadership
    create: true
    fields:
      - { name: relation, label: Relation, widget: string, hint: "eg. 'advisor', 'leadersip', or 'development'"}
      - { name: name, label: Name, widget: string }
      - { name: title, label: Title, widget: string }
      - { name: description, label: Description, widget: string }
      - { name: headshot, label: Headshot, widget: image }
      - { name: email, label: Email, widget: string }
      - { name: linkedin, label: LinkedIn, widget: string, hint: "username only- not full link!" }
  - name: links
    label: Links
    files: 
      - file: src/markdown/links/sociallinks.md
        name: sociallinks
        label: Social Links
        fields:
          - {name: twitter, label: Twitter, widget: string}
          - {name: instagram, label: Instagram, widget: string}
          - {name: linkedin, label: LinkedIn, widget: string}
          - {name: youtube, label: Youtube, widget: string}

