backend:
  name: github
  repo: MUBlockchain/website

media_folder: static/assets
collections:
  - label: blog
    name: Blog
    folder: static/assets/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - label: Featured Image
        name: thumbnail
        widget: image
        media_library: 
          config:
            multiple: false
      - { name: body, label: Body, widget: markdown }
  - label: schedule
    name: Schedule
    folder: static/assets/schedule
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - label: Featured Image
        name: thumbnail
        widget: image
        media_library: 
          config:
            multiple: false
      - { name: body, label: Body, widget: markdown }
