backend:
  name: github
  repo: MUBlockchain/website

media_folder: static/assets/images
collections:
  - label: blog
    name: Blog
    folder: static/assets/blog
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: description, label: Description for SEO }
      - { name: thumbnail, label: Featured image, widget: image}
      - { name: body, label: Body, widget: markdown }
  - label: schedule
    name: Schedule
    folder: static/assets/schedule
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: description, label: Description for SEO }
      - { name: thumbnail, label: Featured image, widget: image}
      - { name: body, label: Body, widget: markdown }
