# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.19.0
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Deploy Website to Apache (https://mubc.io) with SSH
      uses: appleboy/ssh-action@master
      with:
        node-version: 12.19.0
        script: sh ci.sh
        host: ${{ secrets.CI_HOST }}
        username: "ci"
        key: ${{ secrets.CI_SSH_KEY }}
